version: "3.9"  # Use a newer version for features like profiles

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - judge-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - judge-network

networks:
  judge-network:
    driver: bridge
