version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    # ⛔ REMOVE this volume so build artifacts aren't overwritten
    # volumes:
    #   - ./frontend:/app
    depends_on:
      - backend
